"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import os

SECRET_KEY = os.environ.get('SECRET_KEY', 'clave-local-desarrollo')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = ['*']

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Api',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_TZ = True




# ---> Configuración de correo electrónico para enviar alertas automáticas
EMAIL_HOST = 'smtp.gmail.com'
# ---> Puerto de salida para el servidor SMTP
EMAIL_PORT = 587
# ---> Habilitar TLS para la conexión segura
EMAIL_USE_TLS = True
# ----> Email de Origen agregar el suyo(empresa)
# lee del .env si existe, sino usa el Gmail que ya tenías
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'gareispablo6@gmail.com')
# ---> Contraseña de la cuenta de correo (generada desde la cuenta de Gmail)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'nqkfbzffzlgfjbdk')


# IMPORTANTE: con Resend sin dominio verificado, solo se puede enviar al correo
# de la cuenta de Resend (gustavoestevez863@gmail.com).
AIRSENSE_ALERT_EMAIL = os.environ.get('AIRSENSE_ALERT_EMAIL', 'gustavoestevez863@gmail.com')

# ---> Configurar RESEND_API_KEY como variable de entorno en Railway.
#     Pasos:
#     1. Entrá a https://resend.com y creá una cuenta (gratis).
#     2. Andá a https://resend.com/api-keys y clic en "Create API Key".
#     3. Copiá la key que te muestra (empieza con "re_..."). Solo se ve una vez.
#     4. Entrá a https://railway.app → tu proyecto AirSense → servicio Django.
#     5. Pestaña "Variables" → "New Variable" (o "Raw Editor").
#     6. Nombre: RESEND_API_KEY   Valor: pegá la key de Resend.
#     7. (Opcional) AIRSENSE_ALERT_EMAIL = mail donde querés recibir alertas.
#        Sin dominio verificado en Resend, solo llega al mail de tu cuenta Resend.
#     8. Guardá y esperá el redeploy automático (o clic en "Deploy").
#     9. Probá: abrí el dashboard con datos en alerta o mandá un correo manual.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
# Remitente para Resend: se puede usar 'onboarding@resend.dev' sin verificar dominio.
AIRSENSE_RESEND_FROM = os.environ.get('AIRSENSE_RESEND_FROM', 'AirSense <onboarding@resend.dev>')


